In [0]:
o  bbsfrom google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


**Load the data**

In [0]:
import pandas as pd
import h5py
import numpy as np

data = h5py.File('/content/drive/My Drive/Colab Notebooks/SVHN_single_grey1.h5', 'r')


In [0]:
print(list(data.keys()))

['X_test', 'X_train', 'X_val', 'y_test', 'y_train', 'y_val']


**Extract the data into variables**

In [0]:
X_train = data.get('X_train')
y_train = data.get('y_train')
X_val = data.get('X_val')
y_test = data.get('y_test')
X_test = data.get('X_test')
y_val = data.get('y_val')

In [0]:
X_train=np.array(X_train)
X_test=np.array(X_test)
X_val=np.array(X_val)

In [0]:
X_train=X_train.reshape(42000,32*32)
X_test=X_test.reshape(18000,32*32)
X_val=X_val.reshape(60000,32*32)

Perform KNN classifier :

In [0]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Since KNN is taking too much time to complete one cycle, considering optimum K value as 5

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)
print("k=%d, accuracy=%.2f%%" % (5, (model.score(X_val, y_val)) * 100))
predictions = model.predict(X_test)

k=5, accuracy=62.42%


**Report & Confusion matrix**

```
# This is formatted as code
```



In [0]:
print("Classification Report :")
print(classification_report(y_test, predictions))

print ("Confusion matrix")
print(confusion_matrix(y_test,predictions))

Classification Report :
              precision    recall  f1-score   support

           0       0.38      0.66      0.48      1814
           1       0.44      0.70      0.54      1828
           2       0.55      0.52      0.53      1803
           3       0.42      0.39      0.41      1719
           4       0.67      0.61      0.64      1812
           5       0.48      0.36      0.41      1768
           6       0.47      0.38      0.42      1832
           7       0.72      0.58      0.64      1808
           8       0.42      0.33      0.37      1812
           9       0.52      0.36      0.43      1804

    accuracy                           0.49     18000
   macro avg       0.51      0.49      0.49     18000
weighted avg       0.51      0.49      0.49     18000

Confusion matrix
[[1201   60   44   37   45   45  129   31  109  113]
 [ 125 1285   83   81   84   36   36   58   18   22]
 [ 126  252  932  115   44   44   28  128   69   65]
 [ 164  255  166  677   54  157   36   46

**Observations on KNN :**


1.   KNN is taking very long time to complete which is not applicable
2.   The accuracy, precision and recall are also not very commendable
3.   More than half of the classifications are incorrect for each classifier as per the confusion matrix



**Load the data into Arrays to be loaded into the Neural Network**

In [0]:
import tensorflow as tf

X_train = np.array(data.get('X_train'))
y_train = np.array(data.get('y_train'))
X_val = np.array(data.get('X_val'))
y_test = np.array(data.get('y_test'))
X_test = np.array(data.get('X_test'))
y_val = np.array(data.get('y_val'))

tf.reset_default_graph()
y_train=tf.keras.utils.to_categorical(y_train,num_classes=10)
y_val=tf.keras.utils.to_categorical(y_val,num_classes=10)
#y_test=tf.keras.utils.to_categorical(y_test,num_classes=10)

**Create a Keras graph with input layers, hidden layers and output**

In [0]:
model = tf.keras.models.Sequential()

In [0]:
model.add(tf.keras.layers.Reshape((1024,),input_shape=(32,32,)))
model.add(tf.keras.layers.BatchNormalization())

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [0]:
model.add(tf.keras.layers.Dense(150,activation='relu'))
model.add(tf.keras.layers.Dense(100,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

In [0]:
model.fit(X_train,y_train,validation_data=(X_val,y_val),epochs=15,batch_size=42)

Train on 42000 samples, validate on 60000 samples
Epoch 1/15
42000/42000 [==============================] - 7s 173us/sample - loss: 1.7932 - acc: 0.4056 - val_loss: 1.2517 - val_acc: 0.6288
Epoch 2/15
42000/42000 [==============================] - 7s 166us/sample - loss: 1.1759 - acc: 0.6414 - val_loss: 0.9836 - val_acc: 0.7083
Epoch 3/15
42000/42000 [==============================] - 7s 169us/sample - loss: 1.0015 - acc: 0.6945 - val_loss: 0.8574 - val_acc: 0.7484
Epoch 4/15
42000/42000 [==============================] - 7s 169us/sample - loss: 0.8985 - acc: 0.7253 - val_loss: 0.7770 - val_acc: 0.7727
Epoch 5/15
42000/42000 [==============================] - 7s 169us/sample - loss: 0.8181 - acc: 0.7508 - val_loss: 0.7167 - val_acc: 0.7887
Epoch 6/15
42000/42000 [==============================] - 8s 183us/sample - loss: 0.7634 - acc: 0.7665 - val_loss: 0.6636 - val_acc: 0.8088
Epoch 7/15
42000/42000 [==============================] - 7s 170us/sample - loss: 0.7258 - acc: 0.7798 - val_l

In [0]:
predictions = model.predict_classes(X_test)

**Accuracy of Neural Network on Test data**

In [0]:
model.evaluate(X_test, tf.keras.utils.to_categorical(y_test,num_classes=10))

18000/18000 [==============================] - 1s 49us/sample - loss: 0.6060 - acc: 0.8297


[0.606020360827446, 0.8297222]

**Report & Confusion matrix**

In [0]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predictions))

[[1575   31    5   32   18   14   58   20   14   47]
 [  22 1571   17   40   43   11   31   47   32   14]
 [  18   29 1504   57   25   18   10   69   33   40]
 [  17   40   33 1341   12  115   45   43   47   26]
 [  25   57   27   21 1547   17   50   12   24   32]
 [  15   19   10   86    8 1473   88   15   32   22]
 [  43   25   14   30   25   92 1485   18   85   15]
 [  12   56   61   31   12    9   27 1560   19   21]
 [  26   55   21   59   12   50  113   11 1417   48]
 [  52   39   31   48   16   46   25   21   44 1482]]


**Observations on Neural Network :**


1.   A lot faster than KNN
2.   Accuracy, recall and precision of Neural Network are impressive



In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.84      0.87      0.85      1814
           1       0.73      0.90      0.81      1828
           2       0.81      0.85      0.83      1803
           3       0.78      0.78      0.78      1719
           4       0.88      0.86      0.87      1812
           5       0.82      0.81      0.82      1768
           6       0.87      0.79      0.83      1832
           7       0.88      0.86      0.87      1808
           8       0.87      0.75      0.80      1812
           9       0.81      0.80      0.81      1804

    accuracy                           0.83     18000
   macro avg       0.83      0.83      0.83     18000
weighted avg       0.83      0.83      0.83     18000

